name: Docker build

on:
  push:
    tags:
      - "v[0-9].[0-9]+.[0-9]+"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  image:
    runs-on: ubuntu-24.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Calculate image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ github.repository }},enable=${{startsWith(github.ref, 'refs/tags/v')}}
          tags: |
            type=semver,pattern={{version}}
            type=sha,prefix=,enable=${{startsWith(github.ref, 'refs/tags/v') == 'false' }}
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  helm:
    # credits to https://github.com/fabianlee/google-hello-app-logging-multiarch/blob/main/.github/workflows/github-actions-buildOCI.yml
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
    needs: image
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: bitdeps/helm-oci-charts-releaser@v0.1.4
        with:
            oci_registry: ${{ env.REGISTRY }}/${{ env.GITHUB_REPOSITORY_OWNER }}
            oci_username: ${{ env.GITHUB_REPOSITORY_OWNER }}
            oci_password: ${{ secrets.GITHUB_TOKEN }}
            github_token: ${{ secrets.GITHUB_TOKEN }}
            skip_gh_release: true
            tag_name_pattern: "{chartName}-chart"
